#!/usr/bin/env python
import argparse
import sys
import os
import subprocess

from llab.auth import ssh_user


def build_parser(subparsers):
    # Various verification related commands
    verify_group = subparsers.add_argument_group(
        'Verify', 'Commands for verifying a user permission against a project')
    verify_group.add_argument('--user',
                              help='Verify a user permission',
                              metavar='USER_ID')
    verify_group.add_argument('project',
                              help='Verify against project',
                              metavar='PROJECT_SLUG')


def parse_args(args):
    # Fetch user information
    user_id = args.user
    project_path = args.project

    # Process verification based args
    if user_id or project_path:
        if not user_id or not project_path:
            sys.exit('--project and --verify are required for this command')
        project, user = ssh_user.authenticate(user_id, project_path)
        os.execvp('git-upload-pack', ['', project.get_absolute_path()])

    sys.exit("false")


if __name__ == '__main__':
    try:
        parser = argparse.ArgumentParser(description='llab upload-receive tool')
        build_parser(parser)
        parse_args(parser.parse_args())
    except ssh_user.AuthenticationError as e:
        sys.exit(e)
